/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ads;

//import HomeScreen;
import java.sql.*;

/**
 *
 * @author Athang
 */
public class initializetable extends javax.swing.JFrame {

    /**
     * Creates new form initializetable
     */
    public initializetable(String movie,String url) {
        initComponents();
        try{  
			Class.forName("com.mysql.jdbc.Driver");  
  
			Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/MTBS","root","shreyata@06");  
  

  
			Statement stmt=con.createStatement();  
                           int i;
                           char c;
                           //String movie="BatmanvsSuperman";
                           
			//ResultSet rs=stmt.executeQuery("select * from emp");
                        //int aa=stmt.executeUpdate("create table "+movie+"(seat_no varchar(5) not null,"+movie+"1115 varchar(1) not null,"+movie+"0330 varchar(1) not null,"+movie+"0600 varchar(1) not null);");
                        int bb=stmt.executeUpdate("insert into movies value('"+movie+"','"+url+"');");
                       /*for(c='A';c<='H';c++)
                       {
                           
                            for(i=1;i<=8;i++)
                            {    String s=Character.toString(c);
                                s=s+Integer.toString(i);
                                             
                                int a=stmt.executeUpdate("insert into "+movie+" values('"+s+"','0','0','0')");
                                //int b=stmt.executeUpdate("update ddlj set ddlj1115='1' where seat_no='"+s[i]+"';");
                                //System.out.println(s);
                            }
                       }*/
                       /*for(i=0;i<seatcount;i++)
                       {
                           int a=stmt.executeUpdate("insert into ddlj values('"+s+"','0','0')");
                       }
                       ResultSet rs=stmt.executeQuery("select * from ddlj where seat_no='H7';");
                       String s1=rs.getString(2);
                       
                       System.out.println(s1);*/
                       //String s="H7";
                       //int b=stmt.executeUpdate("update ddlj set ddlj1115='0' where seat_no='"+s+"';");
				con.close();  
  
	}catch(Exception e){ 
		e.printStackTrace();
		} 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){  
	/*try{  
			Class.forName("com.mysql.jdbc.Driver");  
  
			Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/MTBS","root","shreyata@06");  
  

  
			Statement stmt=con.createStatement();  
                           int i;
                           char c;
                           String movie="BatmanvsSuperman";
                           
			//ResultSet rs=stmt.executeQuery("select * from emp");
                        int aa=stmt.executeUpdate("create table "+movie+"(seat_no varchar(5) not null,"+movie+"1115 varchar(1) not null,"+movie+"0330 varchar(1) not null,"+movie+"0600 varchar(1) not null);");
                       for(c='A';c<='H';c++)
                       {
                           
                            for(i=1;i<=8;i++)
                            {    String s=Character.toString(c);
                                s=s+Integer.toString(i);
                                             
                                int a=stmt.executeUpdate("insert into "+movie+" values('"+s+"','0','0','0')");
                                //int b=stmt.executeUpdate("update ddlj set ddlj1115='1' where seat_no='"+s[i]+"';");
                                //System.out.println(s);
                            }
                       }
                       /*for(i=0;i<seatcount;i++)
                       {
                           int a=stmt.executeUpdate("insert into ddlj values('"+s+"','0','0')");
                       }
                       ResultSet rs=stmt.executeQuery("select * from ddlj where seat_no='H7';");
                       String s1=rs.getString(2);
                       
                       System.out.println(s1);*/
                       //String s="H7";
                       //int b=stmt.executeUpdate("update ddlj set ddlj1115='0' where seat_no='"+s+"';");
				/*con.close();  
  
	}catch(Exception e){ 
		e.printStackTrace();
		} */
  
	}  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
